---
- hosts: localhost
  connection: local
  tasks:
    - name: Ensure Docker image is built from the test Dockerfile.
      docker_image:
        name: django-ansible
        source: build
        build:
          path: djangoansible
        state: present
    - name: Ensure the test container is running.
      docker_container:
        image: django-ansible:latest
        name: django-ansible
        state: started
        ports: "8000:8000"
